/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  TermsRoute: typeof TermsRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  TermsRoute: TermsRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
